### ISSUE TITLE
NOTE: Nebula Java is not thread-safe.

### ISSUE THREAD

**Issue by zcw5116** [vesoft-inc/nebula-java#261]
from doc: NOTE: Nebula Java is not thread-safe.
what does this mean? 
Using Nebula Java is not a commended way ?

**Comment by Nicole00** [comment]
1. Nebula Java SDK does not support to use the same client in multi-threads, because one thrift connect  is not allowed to be used in multiple threads at the same time. But if you want to use it in multi-threads, please refer to issue https://github.com/vesoft-inc/nebula-java/issues/171
2. You can use Nebula Java SDK to access Nebula Graph, just to know that it's not friendly to use it in multi-threads.
